services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 5434:5432

    flask-app:
        build: ./backend
        ports:
            - 5000:5000
        depends_on:
            - db
        environment:
            - FLASK_ENV=development

    frontend:
        build: ./frontend
        ports:
            - 3000:80
        depends_on:
            - db
